# Generated by Django 5.0.6 on 2024-05-24 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_venta', models.CharField(max_length=50)),
                ('tipo_transaccion', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('a_plazos', models.SmallIntegerField(default=0)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=20)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('observacion_proforma', models.TextField(blank=True, null=True)),
                ('estado', models.SmallIntegerField(default=1)),
                ('reingreso', models.SmallIntegerField(default=0)),
                ('cliente', models.CharField(max_length=50)),
                ('usuario', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('espesor', models.FloatField(blank=True, null=True)),
                ('ancho', models.FloatField(blank=True, null=True)),
                ('largo', models.FloatField(blank=True, null=True)),
                ('largo_mt', models.FloatField(blank=True, null=True)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('estado_inventario', models.TextField(blank=True, null=True)),
                ('cantidad', models.IntegerField()),
                ('precio_venta', models.FloatField()),
                ('subtotal', models.FloatField(blank=True, null=True)),
                ('total_pie', models.FloatField(blank=True, null=True)),
                ('reingreso', models.SmallIntegerField(default=0)),
                ('especie', models.CharField(max_length=50)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle', to='venta_app.venta')),
            ],
        ),
    ]
