# Generated by Django 5.0.6 on 2024-05-25 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenDespacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_despacho', models.IntegerField()),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta_app.venta')),
            ],
        ),
    ]
