# Generated by Django 5.0.6 on 2024-05-25 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta_app', '0003_ingreso_tipoingresoegreso_ingresoventa_pago_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_nota', models.IntegerField()),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta_app.venta')),
            ],
        ),
        migrations.CreateModel(
            name='Proforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_proforma', models.IntegerField()),
                ('puesto_obra', models.TextField()),
                ('tipo_cambio', models.TextField()),
                ('condiciones_entrega', models.TextField()),
                ('tiempo_entrega', models.TextField()),
                ('forma_entrega', models.TextField()),
                ('forma_pago', models.TextField()),
                ('nombre_dirigido', models.TextField()),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta_app.venta')),
            ],
        ),
    ]
