# Generated by Django 5.0.6 on 2024-05-26 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta_app', '0004_notaventa_proforma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='cliente',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='venta',
            name='tipo_transaccion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='venta',
            name='usuario',
            field=models.CharField(max_length=255),
        ),
    ]
