# Generated by Django 5.0.6 on 2024-05-26 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta_app', '0005_alter_venta_cliente_alter_venta_tipo_transaccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='venta_app.venta'),
        ),
    ]
