# Generated by Django 5.0.6 on 2024-05-26 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta_app', '0006_alter_pago_venta'),
    ]

    operations = [
    ]
