# Generated by Django 5.0.6 on 2024-06-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta_app', '0007_auto_20240526_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proforma',
            name='condiciones_entrega',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='proforma',
            name='forma_entrega',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='proforma',
            name='forma_pago',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='proforma',
            name='nombre_dirigido',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='proforma',
            name='puesto_obra',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='proforma',
            name='tiempo_entrega',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='proforma',
            name='tipo_cambio',
            field=models.CharField(max_length=50),
        ),
    ]
