# Generated by Django 5.0.6 on 2024-06-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta_app', '0008_alter_proforma_condiciones_entrega_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='tipo_pago',
            field=models.SmallIntegerField(default=0),
        ),
    ]
