# Generated by Django 5.0.6 on 2024-06-10 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta_app', '0009_pago_tipo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='monto_gift_card',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='numero_tarjeta',
            field=models.CharField(blank=True, max_length=19, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='pago',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='tipo_pago',
            field=models.IntegerField(choices=[(1, 'Efectivo'), (2, 'Gift Card'), (3, 'Tarjeta'), (4, 'Otros')]),
        ),
    ]
