# Generated by Django 5.0.6 on 2024-06-10 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta_app', '0010_pago_monto_gift_card_pago_numero_tarjeta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
